apiVersion: operator.ibm.com/v1alpha1
kind: AuditLogging
metadata:
  name: example-auditlogging
spec:
  fluentd:
    enabled: true
    imageRegistry: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/
    imageTag: v1.6.2-ruby
    pullPolicy: IfNotPresent
    journalPath: /var/log/journal
    elasticsearch: 
      scheme: http
  policyController:
    verbosity: "0"
