apiVersion: operator.ibm.com/v1alpha1
kind: AuditLogging
metadata:
  name: example-auditlogging
spec:
  fluentd:
    enabled: true
    imageRegistry: quay.io/opencloudio/
    imageTag: v1.6.2-ruby25
    pullPolicy: IfNotPresent
    journalPath: /var/log/journal
    cloudPak:
      sourceTag: mcm-audit
      filterJSON: true
  policyController:
    verbosity: "0"
